version: '3'

services:
  nginx:
    image: nginx:1.18-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db

  db:
    image: mysql:5.7.22
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.mysql_data:/var/lib/mysql

  app:
    image: agenciaego/php:7.2
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  
  npm:
    image: node:12.16.2
    volumes:
      - ./:/var/www/html
      - ./.docker/node-entrypoint.sh:/usr/local/bin/node-entrypoint.sh
    working_dir: /var/www/html
    entrypoint: ['node-entrypoint.sh']